name: Build processed formats

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.11'
      
      - name: Run Python script
        run: python tool/build.py

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Built processed
          add_options: '-f'

